### ISSUE TITLE
Does not read config

### ISSUE THREAD

**Issue by 0Karakurt0** [skyme5/polybar-forecast#1]
Welll... Title is quite self-explanatory.
I placed config.toml in the same directory, but it still complaned about missing keys.

**Comment by skyme5** [comment]
Hey @0Karakurt0, sorry but reading config file is not implemented yet. You can supply options as command line arguments instead. 
```text
 -k, --api-key             Your unique openweathermap.org API key.
 -c, --city-id             City ID.
 -u, --units               Units of measurement. standard, metric and imperial
                           units are available. If you do not use the units
                           parameter, standard units will be applied by default.
 -l, --language            You can use this parameter to get the output in your
                           language. (Default: en.)
 -f, --enable-forcast      Include forcast in result.
```
To find city id read [this](https://www.dmopress.com/openweathermap-howto/#:~:text=Get%20your%20OpenWeatherMap%20City%20ID).

**Comment by 0Karakurt0** [comment]
That's exactly how I made it to work)
And you already removed confusing line from README, so it's ok now
