### ISSUE TITLE
Separating %output% from its prefix

### ISSUE THREAD

**Issue by ggteixeira** [skyme5/polybar-forecast#2]
Hi! I just started using your awesome module, and I'd like to know if it's possible to separate the weather icon from the weather result. Some people like to put different icon colors in their rice, it would be nice to have it in `polybar-forecast`. I would do it myself and submit a PR, but I know nothing about Rust 😆

**Comment by skyme5** [comment]
@vibraniumdev Thank you for using this. This project is a fork from [polybar-forecast by kamek-pf](https://github.com/kamek-pf/polybar-forecast) and I think the original project would resolve your issue. Let me know if you need any help.

**Comment by ggteixeira** [comment]
Thanks, @skyme5!
